version: "3.8"

services:
  board-service:
    container_name: product_service
    image: ${DOCKER_USERNAME}/product_service:latest  # Docker Hub 이미지 사용
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_HOST: ${EUREKA_HOST}
    networks:
      - backend

networks:
  backend:
    external: true