spring:
  datasource:
    url: jdbc:mysql://${EUREKA_HOST}:3310/${AWS_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}