server:
  port: 8083
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: product-service
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/