spring:
  datasource:
    url: jdbc:mysql://${EC2_DB}:3306/piece_of_cake
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${EC2_HOST2}:10000,${EC2_HOST2}:10001,${EC2_HOST2}:10002
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

openai:
  api:
    model: gpt-4o
    key: ${GPT_API_KEY}
    temperature: 0.0
    maxTokens: 500

    url:
      model: https://api.openai.com/v1/models
      model-list: https://api.openai.com/v1/models
      prompt: https://api.openai.com/v1/chat/completions